Parameters:
  TestVPC:
    Description: VPC used to deploy resources
    Type: AWS::EC2::VPC::Id
  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
  AMItoUse:
    Type: AWS::EC2::Image::Id
    Description: AMI to use for base image
Resources:
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our test host
      VpcId:
        Ref: TestVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AMItoUse
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: "WebAccessSecurityGroup"
          SubnetId: !Ref PublicSubnet
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          #
          # Install http server
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
